/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GalleryFooter: typeof import('./src/gallery/components/gallery/footer.vue')['default']
    GalleryHeader: typeof import('./src/gallery/components/gallery/header.vue')['default']
    GalleryLoadMoreTile: typeof import('./src/gallery/components/gallery/load-more-tile.vue')['default']
    GalleryTile: typeof import('./src/gallery/components/gallery/tile.vue')['default']
    GalleryTilesBox: typeof import('./src/gallery/components/gallery/tiles-box.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
